services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    ports:
      - 8090:8080
    command: mlflow server --host 0.0.0.0 --port 8080 --backend-store-uri /mlflow/backend --default-artifact-root /mlflow/artifacts
    volumes:
      - ${MLFLOW_VOLUME}:/data/db