FROM bitnami/spark:3.5.5

USER root

ENV PATH="/.local/bin:${PATH}"

COPY dev-requirements.txt .
RUN pip install --no-cache-dir -r dev-requirements.txt

ENV KAFKA_BROKER_URI="kafka:9092"
ENV MONGO_DB_URI="mongodb://mongo:27017"
ENV MLFLOW_URI="http://mlflow:8080"

