services:
  data-acquisition-app:
    build: ./data-acquisition-app
    environment:
      - KAFKA_BROKER_URI=kafka:9092
      - GITHUB_TOKEN=${GITHUB_TOKEN}

    depends_on:
      kafka:
        condition: service_healthy

  data-ingestion-app:
    build: ./data-ingestion-app
    environment:
      - KAFKA_BROKER_URI=kafka:9092
      - MONGO_DB_URI=mongodb://mongo:27017
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started

  mongo:
    image: mongo:8.0.4
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_VOLUME}:/data/db

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9094:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker # One node will act as the controller and a broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5