version: "3.8"
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/app  # Montre le répertoire actuel dans /app (utile pour le développement)
    restart: unless-stopped
