# Utilise une image de base avec Python
FROM python:3.9-slim

# Mettre à jour pip
RUN pip install --upgrade pip

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers du projet dans le conteneur
COPY . /app

# Installer les dépendances directement via pip
RUN pip install fastapi uvicorn mlflow scikit-learn gensim spacy joblib numpy

# Exposer le port 8000 pour accéder à l'API
EXPOSE 8000

# Commande pour lancer l'application FastAPI avec Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
