name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

env:
  MONGO_VOLUME: ${{ vars.MONGO_VOLUME }}

jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and start the Docker containers
      run: docker compose up --build -d
    - name: Stop and remove Docker containers
      run: docker compose down
